In [6]:
import torch
from torch.autograd import Variable

## Tensors and Variables

In [11]:
#This is a tensor, but without gradient accumulation
a = torch.ones(2,2)
print(a,a.requires_grad)

tensor([[ 1.,  1.],
        [ 1.,  1.]]) False


In [12]:
#This is a Variable, for accumulating gradients
b = Variable(torch.ones(2,2), requires_grad=True)
print(b,b.requires_grad)

tensor([[ 1.,  1.],
        [ 1.,  1.]]) True


In [14]:
#But I can create a tensor that works like variables
a = torch.ones((2,2),requires_grad=True)
#and voila
print(a,a.requires_grad)

tensor([[ 1.,  1.],
        [ 1.,  1.]]) True


In [25]:
#this is equal as the first cell, the requires_grad defaults to False
a = Variable(torch.ones(2,2))
print(a,a.requires_grad)

tensor([[ 1.,  1.],
        [ 1.,  1.]]) False


## Gradients

In [15]:
x = torch.rand((2,2),requires_grad=True)
x

tensor([[ 0.4223,  0.5200],
        [ 0.1291,  0.7323]])

In [16]:
y = 5 * x + (x**3)/2
y

tensor([[ 2.1493,  2.6705],
        [ 0.6464,  3.8577]])

In [17]:
out = y.mean()
out

tensor(2.3310)

In [18]:
out.backward()
x.grad

tensor([[ 1.3169,  1.3514],
        [ 1.2562,  1.4511]])