# Imports

In [2]:
import numpy as np
import torch


## Bridge

In [7]:
matrix_a = np.arange(10).reshape(-1,2)
matrix_a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
t_a = torch.from_numpy(matrix_a)
t_a
t_a[-2:]*=2
t_a

tensor([[  0,   1],
        [  2,   3],
        [  4,   5],
        [ 24,  28],
        [ 32,  36]])

In [15]:
matrix_b = t_a.numpy()
print(matrix_b,'\n')
print(matrix_a)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [24 28]
 [32 36]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [24 28]
 [32 36]]


## CPU or GPU

In [25]:
device = 'cpu'
if(torch.cuda.is_available()):
    torch.cuda.manual_seed_all(1982)
    device='gpu'
    t_a.cuda() #converting tensor to GPU version
else:
    t_a.cpu() #Converting tensor to CPU
print(device)


cpu


## Tensor Operations

In [40]:
print(t_a.size())
print(t_a.view(10)) # Just viewing inline, without reshape
print(t_a)
print(t_a.view(2,5)) # Verbose Transpose 
print(torch.t(t_a)) # transpose without reshape

torch.Size([5, 2])
tensor([  0,   1,   2,   3,   4,   5,  24,  28,  32,  36])
tensor([[  0,   1],
        [  2,   3],
        [  4,   5],
        [ 24,  28],
        [ 32,  36]])
tensor([[  0,   1,   2,   3,   4],
        [  5,  24,  28,  32,  36]])
tensor([[  0,   2,   4,  24,  32],
        [  1,   3,   5,  28,  36]])


## Math operations

In [43]:
a = torch.ones(3,3)
b = torch.ones(3,3)
soma = a+b
soma

tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]])

In [51]:
soma = None
soma = torch.add(a,b) # Another way of summing
soma

tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]])

In [52]:
c = torch.ones(3,3)
soma.add(c)
print(soma) # soma didn't change because its out of place
soma.add_(c) #inplace addition
soma

tensor([[ 2.,  2.,  2.],
        [ 2.,  2.,  2.],
        [ 2.,  2.,  2.]])


tensor([[ 3.,  3.,  3.],
        [ 3.,  3.,  3.],
        [ 3.,  3.,  3.]])

## Mean

In [61]:
a = torch.arange(10).reshape(5,-1)
print(a)
#mean of dimension 0 eg rows, eg summing all row elements and dividing by the number of rows
mean_dim_0 = a.mean(dim=0) 
mean_dim_0

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6.,  7.],
        [ 8.,  9.]])


tensor([ 4.,  5.])

In [63]:
mean_dim_1 = a.mean(dim=1)
print(mean_dim_1)
mean_dim_1.size()

tensor([ 0.5000,  2.5000,  4.5000,  6.5000,  8.5000])


torch.Size([5])

In [59]:
a.mean() #mean of all elements

tensor(4.5000)

In [64]:
a.std()

tensor(3.0277)

In [65]:
a.var()

tensor(9.1667)